apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: pi
  namespace: runai-test  # Specify the namespace as runai-test
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          schedulerName: runai-scheduler  # Use the runai-scheduler
          containers:
          - image: docker.io/vivekkolasani1996/vivek-mpi-nonroot:v1
            name: mpi-launcher
            securityContext:
              runAsUser: 1001  # Run the launcher as user with UID 1001
            command:
            - mpirun
            args:
            - -np
            - "2"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - /usr/bin/python3
            - /scripts/mpi_torch.py  # Python script to be executed by the launcher
            resources:
              limits:
                cpu: 1
                memory: 1Gi
    Worker:
      replicas: 2
      template:
        spec:
          schedulerName: runai-scheduler  # Use the runai-scheduler
          containers:
          - image: docker.io/vivekkolasani1996/vivek-mpi-nonroot:v1
            name: mpi-worker
            securityContext:
              runAsUser: 1001  # Run the workers as user with UID 1001
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config  # Assuming this is your sshd_config path
            resources:
              limits:
                cpu: 1
                memory: 1Gi

