apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: dist-int
  namespace: runai-sony
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - name: mpi-launcher
            image: mpioperator/tensorflow-benchmarks:latest
            command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "2"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
            - --model=resnet101
            - --batch_size=64
            - --variable_update=horovod
              echo "Horovod run completed, sleeping infinitely";
              sleep infinity
            resources:
              limits:
                nvidia.com/gpu: 1
              requests:
                nvidia.com/gpu: 1
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - name: mpi-worker
            image: mpioperator/tensorflow-benchmarks:latest
            command:
            - sh
            - -c
            - "sleep infinity"
            resources:
              limits:
                nvidia.com/gpu: 1
              requests:
                nvidia.com/gpu: 1
